name: Update user data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Sunday at 00:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.4'
          cache: 'pip'
      
      - name: Run fetch script
        working-directory: ./gh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FOLDER: '../website/public'
          QUERY_BATCH_SIZE: 10
        run: |
          pip install -r requirements.txt
          python fetch.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add website/public/
          git diff --quiet && git diff --staged --quiet || (git commit -m "auto: update leaderboard data" && git push)


  re-deploy:
    needs: update

    runs-on: ubuntu-latest
    
    steps:
      - name: Re-deploy to GitHub Pages
        uses: ./.github/workflows/deploy.yaml
